//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserRegistrationWithEF_EDM_DB_First_CRUD.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class User
    {
        public int Id { get; set; }
        
        [Required]
        [Remote("CheckUserName","Users", AdditionalFields = "Id", ErrorMessage ="This Username is not available!")]
        public string Username { get; set; }
        [Required]
        public string Firstname { get; set; }
        [Required]
        public string Lastname { get; set; }
        [DataType(DataType.Password)]
        public string Password { get; set; }
        [Required]
        public string Gender { get; set; }
        [Required]
        public string Phone { get; set; }
        [Required]
        public string Email { get; set; }
        public Nullable<int> Age { get; set; }
        public string State { get; set; }
        public bool ReceiveNewsLetters { get; set; }
        public string Hobbies { get; set; }
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> DateOfSubscription { get; set; }
        public Nullable<int> CountryId { get; set; }
        public string MaritalStatus { get; set; }
        [Required]
        public string Address { get; set; }
        public Nullable<decimal> RegistrationFee { get; set; }
        public virtual Country Country { get; set; }
    }
}
